#!/usr/bin/env node
/**
 * governance-sdk CLI — Interactive project setup
 *
 * Usage:
 *   npx governance-sdk init     Scaffold governance.config.ts (interactive)
 *   npx governance-sdk demo     Zero-setup in-process walkthrough (no network, no API key)
 *   npx governance-sdk connect  Test connectivity to a hosted governance API
 */

import { writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { createInterface } from "node:readline";

const RESET = "\x1b[0m";
const BOLD = "\x1b[1m";
const DIM = "\x1b[2m";
const GREEN = "\x1b[32m";
const CYAN = "\x1b[36m";
const YELLOW = "\x1b[33m";
const RED = "\x1b[31m";
const MAGENTA = "\x1b[35m";

function print(msg: string) {
  process.stdout.write(msg + "\n");
}

function ask(question: string, defaultVal?: string): Promise<string> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const prompt = defaultVal
    ? `${CYAN}?${RESET} ${question} ${DIM}(${defaultVal})${RESET} `
    : `${CYAN}?${RESET} ${question} `;

  return new Promise((resolve) => {
    rl.question(prompt, (answer) => {
      rl.close();
      resolve(answer.trim() || defaultVal || "");
    });
  });
}

function banner() {
  print("");
  print(`${BOLD}${MAGENTA}  governance-sdk${RESET}`);
  print(`${DIM}  Runtime governance for TypeScript AI agents${RESET}`);
  print(`${DIM}  Policy enforcement · Audit trails · Fleet scoring${RESET}`);
  print("");
}

interface InitConfig {
  agentName: string;
  owner: string;
  framework: string;
  blockDangerous: boolean;
  requireApproval: boolean;
  tokenLimit: number;
  useProcessor: boolean;
}

function generateConfigFile(config: InitConfig): string {
  const imports: string[] = [
    "createGovernance",
    "blockTools",
  ];

  const rules: string[] = [];

  if (config.blockDangerous) {
    rules.push(`    blockTools([\n      'shell_exec', 'rm_rf', 'database_drop',\n      'file_delete', 'process_kill',\n    ]),`);
  }

  if (config.requireApproval) {
    imports.push("requireApproval");
    rules.push(`    requireApproval(['data_export', 'email_send', 'payment_process']),`);
  }

  if (config.tokenLimit > 0) {
    imports.push("tokenBudget");
    rules.push(`    tokenBudget(${config.tokenLimit.toLocaleString().replace(/,/g, "_")}),`);
  }

  const importLine = `import { ${imports.join(", ")} } from 'governance-sdk';`;

  let processorSection = "";
  if (config.useProcessor) {
    processorSection = `
// ─── Mastra Processor (framework-level governance) ──────────
// Pass this processor to agent.generate() to govern ALL tool calls
// automatically — no per-tool wrapping needed.

import { GovernanceProcessor } from 'governance-sdk/plugins/mastra-processor';

export const processor = new GovernanceProcessor(governance, {
  agentName: '${config.agentName}',
  owner: '${config.owner}',
  framework: '${config.framework}',
  retryOnBlock: true, // Let the LLM try a different approach
  maxRetries: 2,
});

// Usage:
// const result = await agent.generate(prompt, { processor });
`;
  }

  return `/**
 * governance-sdk configuration
 * Generated by: npx governance-sdk init
 *
 * Docs: https://github.com/scotty595/governance-sdk#readme
 * GitHub: https://github.com/scotty595/governance-sdk
 */

${importLine}

// ─── Governance Instance ────────────────────────────────────
// Central governance configuration for your agent fleet.
// All agents registered here share the same policy rules.

export const governance = createGovernance({
  rules: [
${rules.join("\n")}
  ],
});

// ─── Register Your Agent ────────────────────────────────────
// Call this at agent startup. Returns { id, score, level }.

export async function registerAgent() {
  return governance.register({
    name: '${config.agentName}',
    framework: '${config.framework}',
    owner: '${config.owner}',
    hasAuth: false,       // Set true when you add auth
    hasGuardrails: true,  // You have governance now!
    hasObservability: false,
    hasAuditLog: true,    // Governance provides audit
  });
}
${processorSection}
// ─── Enforce Before Actions ─────────────────────────────────
// Call gov.enforce() before any sensitive operation.
//
// const decision = await governance.enforce({
//   agentId: agent.id,
//   agentName: '${config.agentName}',
//   agentLevel: agent.level,
//   action: 'tool_call',
//   tool: 'shell_exec',
// });
//
// if (decision.blocked) {
//   console.log('Blocked:', decision.reason);
// }
`;
}

async function main() {
  const args = process.argv.slice(2);
  const command = args[0];

  if (command !== "init") {
    print(`${BOLD}governance-sdk${RESET} — Runtime governance for TypeScript AI agents\n`);
    print(`${BOLD}Usage:${RESET}`);
    print(`  npx governance-sdk demo     Run a zero-setup walkthrough (no network, no API key)`);
    print(`  npx governance-sdk init     Set up governance in your project`);
    print(`  npx governance-sdk connect  Test connectivity to a hosted governance API`);
    print(`  npx governance-sdk --help   Show this help message\n`);
    print(`${BOLD}Docs:${RESET} https://github.com/scotty595/governance-sdk#readme`);
    print(`${BOLD}GitHub:${RESET} https://github.com/scotty595/governance-sdk\n`);
    return;
  }

  banner();

  // Check if config already exists
  const configPath = resolve(process.cwd(), "governance.config.ts");
  if (existsSync(configPath)) {
    print(`${YELLOW}!${RESET} governance.config.ts already exists.`);
    const overwrite = await ask("Overwrite?", "no");
    if (!overwrite.toLowerCase().startsWith("y")) {
      print(`${DIM}  Aborted.${RESET}\n`);
      return;
    }
  }

  // Interactive setup
  print(`${BOLD}  Let's set up governance for your project.${RESET}\n`);

  const agentName = await ask("Agent name", "my-agent");
  const owner = await ask("Team/owner", "engineering");

  const frameworkChoice = await ask("Framework (mastra/langchain/vercel-ai/custom)", "mastra");
  const framework = ["mastra", "langchain", "vercel-ai", "openai", "custom"].includes(frameworkChoice)
    ? frameworkChoice
    : "custom";

  const blockDangerous = (await ask("Block dangerous tools? (shell, rm, db drop)", "yes"))
    .toLowerCase().startsWith("y");

  const requireApprovalAnswer = (await ask("Require approval for sensitive actions?", "yes"))
    .toLowerCase().startsWith("y");

  const tokenLimitStr = await ask("Per-session token budget (0 = unlimited)", "100000");
  const tokenLimit = parseInt(tokenLimitStr, 10) || 0;

  const useProcessor = framework === "mastra" &&
    (await ask("Use native Mastra Processor? (recommended)", "yes"))
      .toLowerCase().startsWith("y");

  print("");

  // Generate config
  const config: InitConfig = {
    agentName,
    owner,
    framework,
    blockDangerous,
    requireApproval: requireApprovalAnswer,
    tokenLimit,
    useProcessor,
  };

  const fileContent = generateConfigFile(config);
  writeFileSync(configPath, fileContent, "utf-8");

  // Success output
  print(`${GREEN}✓${RESET} Created ${BOLD}governance.config.ts${RESET}\n`);
  print(`${BOLD}  Next steps:${RESET}\n`);
  print(`  ${CYAN}1.${RESET} Import governance in your agent:`);
  print(`     ${DIM}import { governance, registerAgent } from './governance.config';${RESET}`);
  print("");
  print(`  ${CYAN}2.${RESET} Register your agent at startup:`);
  print(`     ${DIM}const agent = await registerAgent();${RESET}`);
  print(`     ${DIM}// → { id, score: 42, level: 1 }${RESET}`);
  print("");

  if (useProcessor) {
    print(`  ${CYAN}3.${RESET} Pass the processor to agent.generate():`);
    print(`     ${DIM}import { processor } from './governance.config';${RESET}`);
    print(`     ${DIM}const result = await agent.generate(prompt, { processor });${RESET}`);
    print(`     ${DIM}// Every tool call is now governed automatically${RESET}`);
  } else {
    print(`  ${CYAN}3.${RESET} Enforce before sensitive actions:`);
    print(`     ${DIM}const decision = await governance.enforce({${RESET}`);
    print(`     ${DIM}  agentId: agent.id, action: 'tool_call', tool: 'shell_exec',${RESET}`);
    print(`     ${DIM}});${RESET}`);
  }

  print("");
  print(`  ${BOLD}Docs:${RESET} https://github.com/scotty595/governance-sdk#readme`);
  print(`  ${BOLD}GitHub:${RESET} https://github.com/scotty595/governance-sdk`);
  print("");
}

// ─── Subcommand Router ────────────────────────────────────────

const subcommand = process.argv[2];

if (subcommand === "demo") {
  import("./demo.js").then((m) => m.runDemoCli()).catch((e) => {
    print(`${RED}Error: ${e instanceof Error ? e.message : String(e)}${RESET}`);
    process.exit(1);
  });
} else if (subcommand === "connect") {
  import("./connect.js").then((m) => m.runConnect()).catch((e) => {
    print(`${RED}Error: ${e instanceof Error ? e.message : String(e)}${RESET}`);
    process.exit(1);
  });
} else if (subcommand === "init" || !subcommand || subcommand === "--help" || subcommand === "-h" || subcommand === "help") {
  main().catch((e) => {
    print(`${RED}Error: ${e instanceof Error ? e.message : String(e)}${RESET}`);
    process.exit(1);
  });
} else {
  print(`${RED}Unknown command: ${subcommand}${RESET}`);
  print("");
  print(`${BOLD}Usage:${RESET}`);
  print(`  npx governance-sdk demo      Run a zero-setup walkthrough (no network, no API key)`);
  print(`  npx governance-sdk init      Set up governance in your project`);
  print(`  npx governance-sdk connect   Test connectivity to a hosted governance API`);
  process.exit(1);
}
